### PR TITLE
Pretty print stack traces

### PR DESCRIPTION
**Pull request by andytill**
Improve the crash report UI, #58.

- [x] Show the crash class and reason.
- [x] Pretty print stack traces in crash reports.
- [x] Allow crash reports to be removed from erlyberly.
- [x] Make crash report order obvious using a time stamp.
- [x] Stack trace elements are clickable links to source code.

### CODE REVIEW

**Comment by ruanpienaar** [comment]
Looks great! +1

**Comment by andytill** [comment]
Thanks!  I noticed that `function_clause` errors have the proper stack trace in the `error_info`, that probably goes for others as well, I might just merge it as-is since it is an improvement over what is already there.

**Comment by ruanpienaar** [comment]
Merge it! i've been working on the Preferences pane, and a disconnect button.

**Comment by andytill** [comment]
@ruanpienaar merged. Looking forward to seeing what you have come up with :)

**Pull request merged**
