### PR TITLE
Fix global process names not shown

### PR DESCRIPTION
**Pull request by aboroska**
When a process is globally registered Erlyberly does not show the name
of the process. This patch fixes that. It does not aim fixing global
process handling everywhere, only in the Processes window.

### CODE REVIEW

**Comment by andytill** [comment]
This is awesome, I tested it and it works fine. Are you using an app that is using global for distribution?

Do you think it is an issue that if a process is also locally registered, it overrides the process name? If that is fine for your usage could you add a line to the docs somewhere mentioning that?

**Comment by aboroska** [comment]
Yes, I noticed the problem when I wanted to trace a global gen_server. :)

It never occurred to me that a process can be registered both locally and globally. What would be the use case? I guess it is not that common to justify documenting. Maybe we can wait others to comment.

**Comment by aboroska** [comment]
How about displaying globally registered processes in bold font? That way the user immediately sees how was the process registered. The implementation could be simple as prefixing the process name with 'erlyberly_global_' in Erlang, then removing this prefix in Java.

**Comment by andytill** [comment]
So I think we have a couple of choices:

1) Merge as is. I don't use global so not affected by this change, if anyone doesn't like the behaviour, they can change it later on and PR the improvements.
2) We show the local and global registered names. For example `my_local_srv (my_global_srv)`, anyone using global should recognise the bracketed process name, and the brackets are not shown for non-local processes. The global and local registered names should be sent as separate props in the proplist. Both props are optional. Putting style on part of the text is not so simple in JavaFX I think, so just using text is best.
3) Do both, merge this now, then create an issue for displaying the local **and** global name. The issue would be the docs until it is changed. The issue would actually be a feature request, rather than a bug.

The choice is yours ;)

**Comment by aboroska** [comment]
3. then :)

**Comment by andytill** [comment]
Done, many thanks!

**Comment by andytill** [comment]
Issue created for the proposed extra functionality https://github.com/andytill/erlyberly/issues/135

**Pull request merged**
