### PR TITLE
Open tabs instead of new windows

### PR DESCRIPTION
**Pull request by andytill**
screen shot 2016-03-06 at 16 36 28

### CODE REVIEW

**Comment by ruanpienaar** [comment]
This is amazing.
I had a similar idea about eb tracing instances. 

It's be useful if you were able to keep connecting to more nodes with tabs having the node name as title. That way, you could contain multiple node' traces in tabs, in 1 window :)

**Comment by andytill** [comment]
@ruanpienaar glad you like it :)

The main reason for this is that I can't `alt+tab` between sub windows in gnome 3, at least by default. It could have a few interesting uses, like several tabs with different searches in them.

**Comment by ruanpienaar** [comment]
I meant, as you go along, you can keep connecting to more nodes, and the nodes would also be tabbed, at the top of the ui.

**Comment by ruanpienaar** [comment]
Starting 4 eb's for 4 erlang nodes, is quiet resource intensive ;)

**Comment by andytill** [comment]
Yeah, I think this would need some deep thought to make it usable. For example, If the filtering was better we could have all traces in the same list then put custom filters on them in different tabs, a github like filter might be like `node:mynode`.

Is it memory intensive?

**Comment by ruanpienaar** [comment]
Depends on the amount of tracing, i'll have to test it properly to gather some exact numbers

**Comment by andytill** [comment]
Hopefully we can avoid making the code more complex with optimisations for a while. A couple of these should fix it :) http://www.ebuyer.com/719506-corsair-dominator-platinum-series-128gb-8-x-16gb-ddr4-dram-2400mhz-c14-cmd128gx4m8a2400c14

**Comment by ruanpienaar** [comment]
:satisfied:

**Pull request merged**
